version: '3'
services:
  frontend:
    container_name: tradedashboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "60492:60492"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro